---
- hosts: all
  pre_tasks:
    - name: "Installing which on CentOS"
      yum:
        name: which
        state: present
      when: ansible_distribution == 'CentOS'
    - name: "Installing wget on Debian"
      apt:
        name: wget
        state: present
      when: ansible_distribution == 'Debian'
  roles:
    - role: ansible-telegraf
